version: '2.2'
services:
  consul:
    image: consul:latest
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
#  configservice:
#    build: configservice
#    healthcheck:
#      test: "exit 0"
#    ports:
#      - "8888:8888"
  hystrix:
    build: hystrix
    ports:
      - "8888:8888"
    depends_on:
      - consul
    links:
      - consul:consul