spring:
  application:
    name: hystric-service
  cloud:
    consul:
      discovery:
        instanceid: ${spring.application.name}:${random.value}
      config:
        enabled: true
      host: consul1
      port: 8500
server:
  port: 9999